# Generated by Django 3.1.3 on 2021-02-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.IntegerField()),
                ('product_name', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(max_length=64)),
                ('storage_location', models.CharField(max_length=64)),
                ('team_name', models.CharField(max_length=16)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=32)),
                ('safety_stock', models.IntegerField()),
                ('note', models.TextField()),
            ],
        ),
    ]
