# Generated by Django 3.1.3 on 2021-02-06 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
