# Generated by Django 3.1.3 on 2021-02-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210218_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
