# Generated by Django 3.1.3 on 2021-02-06 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carry_day', models.DateField()),
                ('carry_team', models.CharField(max_length=16)),
                ('receive_company', models.CharField(max_length=32)),
                ('receive_tel', models.CharField(max_length=16)),
                ('receive_user', models.CharField(max_length=16)),
                ('material_name', models.CharField(max_length=64)),
                ('material_info', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=64)),
                ('pack_date', models.DateField()),
                ('production_capacity', models.IntegerField()),
                ('carry_capacity', models.IntegerField()),
                ('residual_quantity', models.IntegerField()),
                ('delivery', models.CharField(max_length=16)),
                ('modify_date', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
