# Generated by Django 3.1.3 on 2021-02-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeout',
            name='carry_capacity',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='takeout',
            name='production_capacity',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='takeout',
            name='residual_quantity',
            field=models.CharField(max_length=32),
        ),
    ]
