# Generated by Django 3.1.3 on 2021-02-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20210206_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeout',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
